### ISSUE TITLE
Add regional outputs to `data_quality_metrics`

### ISSUE THREAD

**Issue by gailin-p** [singularity-energy/open-grid-emissions#227]
Currently, `data_quality_metrics` outputs report proportions of data sources and methods across the entire dataset. These dataset-wide averages may not be representative for smaller BAs. For example, PACW in 2019-2020/v0.1.1 data has a much lower emission rate than real-time estimates (below). When identifying the source of this discrepancy, it would be useful to be able to quickly identify what proportion of the FPC data is CEMS vs shaped EIA-923. More broadly, it would be useful to identify BAs where a majority of fossil generation is shaped EIA-923 data, because we may have lower confidence in the hourly rates in these BAs. 

![Screen Shot 2022-09-12 at 1 26 46 PM](https://user-images.githubusercontent.com/12755256/189718117-d9fba349-5a33-42fa-8c42-cee1316899c9.png)
Difference in PACW OGE emission rate (blue) and real-time emission rate (red) (real-time rate is calculated from EIA-930 per-fuel generation and eGRID 2019 annual average emission rates). In this case, the discrepancy is due to coal generation listed for PACW in EIA-930 data (used to derive the real-time rates).

**Comment by grgmiller** [comment]
Closed with the v.0.2.0 release
